# Generated by Django 4.0.4 on 2022-05-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('email', models.EmailField(default='example@mail.com', max_length=254)),
                ('phone', models.IntegerField(default=998901234567)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=150)),
                ('your_email', models.EmailField(max_length=150, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('majburiyat', models.CharField(max_length=255)),
                ('konikma', models.CharField(max_length=255)),
                ('maosh', models.CharField(max_length=255)),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='applar.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='applar.company')),
            ],
        ),
        migrations.CreateModel(
            name='Singin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Majbur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majburiyat', models.CharField(max_length=255)),
                ('konikma', models.CharField(max_length=255)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applar.job')),
            ],
        ),
    ]
