# Generated by Django 4.0.4 on 2022-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0002_job_jbtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezyume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=150)),
                ('your_email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.IntegerField(default=1234567890)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
