# Generated by Django 4.0.4 on 2022-05-20 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0003_rezyume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezyume',
            name='subject',
        ),
        migrations.AddField(
            model_name='rezyume',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rezyume/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
