# Generated by Django 4.0.4 on 2022-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0004_remove_rezyume_subject_rezyume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezyume',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
