# Generated by Django 4.0.4 on 2022-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0005_alter_rezyume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='your_email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rezyume',
            name='your_email',
            field=models.EmailField(max_length=150),
        ),
    ]
