# Generated by Django 4.0.4 on 2022-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0006_alter_contact_your_email_alter_rezyume_your_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singin',
        ),
    ]
