# Generated by Django 4.0.4 on 2022-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0007_delete_singin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezyume',
            name='image',
            field=models.ImageField(upload_to='rezyume/%Y/%m/%d/'),
        ),
    ]
