# Generated by Django 4.0.4 on 2022-05-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0008_alter_rezyume_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/img')),
            ],
        ),
    ]
