# Generated by Django 4.0.4 on 2022-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0010_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='place',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='salary',
            field=models.CharField(default='defaul title', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
