# Generated by Django 4.0.4 on 2022-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0013_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
