# Generated by Django 4.0.4 on 2022-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0014_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jbtype',
            field=models.CharField(choices=[('Intership', 'Intership'), ('Part-time', 'Part-time'), ('Urgent', 'Urgent')], max_length=255),
        ),
    ]
