# Generated by Django 4.0.4 on 2022-05-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0015_alter_job_jbtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majbur',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majbur', to='applar.job'),
        ),
    ]
