# Generated by Django 4.0.4 on 2022-05-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0016_alter_majbur_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majbur',
            name='konikma',
        ),
        migrations.AlterField(
            model_name='majbur',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applar.job'),
        ),
        migrations.CreateModel(
            name='Konik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konikma', models.CharField(max_length=255)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applar.job')),
            ],
        ),
    ]
