# Generated by Django 4.0.4 on 2022-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0018_alter_konik_jobs_alter_majbur_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
