# Generated by Django 4.0.5 on 2022-06-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applar', '0021_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
